### ISSUE TITLE
No schema validation performed

### ISSUE THREAD

**Issue by zaxbowow** [nuxodin/jema.js#1]
Look a line 499 of schema.js

Is this a joke?

**Comment by nuxodin** [comment]
According to the specification, the format keyword is not for validation. It should only generate annotations and I have not yet implemented annotations.
https://json-schema.org/draft/2020-12/json-schema-validation#name-format-annotation-vocabular

**Comment by zaxbowow** [comment]
Your repo is elegantly written, holds a lot of promise, and I plan to contribute.

Needs a lot of work, but "has good bones", as they say.

Regards,

Eric

**Comment by nuxodin** [comment]
I would be very happy if I could get some help.
My goal is simply to keep the codebase very lean.
