### ISSUE TITLE
Floating point math issue

### ISSUE THREAD

**Issue by zaxbowow** [nuxodin/jema.js#2]
Using schema.js, `-8599.3` fails the schema 

`{"type":"number","multipleOf":0.01}` 

due to schema.js line 465:

`if (Number.isInteger(value / mOf)) return true;`

The appears to be due to the way JavaScript does floating point calculations.

`8599.3 / 0.01 = -859929.9999999999`

Not sure if this is a full and proper generalized fix, but the following change seems as if it would work: 

`if (Number.isInteger(+(value / mOf).toFixed(9))) return true;`

**Comment by nuxodin** [comment]
Thank you for your report!
Can I add you as a contributor?

I updated the lib.

My solution is similar:
`if ( Number.isInteger( +(value / mOf).toPrecision(15) ) ) return true;`

**Comment by zaxbowow** [comment]
Glad to be a contributor.  Fantastic library.

**Comment by nuxodin** [comment]
I thought I could manually add you as a contributor, but apparently I can't.

Can you make a little Pull-Request?

This line, for example, is not needed:
![grafik](https://github.com/nuxodin/jema.js/assets/16326/860d05f0-8dcb-4bf6-849c-01ca9025b884)
