### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by yne** [nuxodin/jema.js#7]
Hi,

Impressive work ! Love your dependency-free single-file approach.

I'm planning on using it on a TypeScript project so I made a typed [schema.ts](https://github.com/user-attachments/files/16570465/schema.ts.txt) version with:
- added some type conversion (in validDate/validTime) to prevent implicit conversion
- fixed some typo (foraign=>foreign, vocal=>vocab)
- added two arguments (fetch/URL) to the `new Schema()` constructor to be platform-agnostic and easyly mockable

If you are interested, I could send a PR along with a new compile step in gh-action to continue publishing the JS version
If you are not interested I will keep it in a fork :)

**Comment by nuxodin** [comment]
Hi, yes i am interested!
But I want to keep it javascript.
Couldn't you specify types in jsdoc, that would be compatible with ts..?

**Comment by yne** [comment]
I've never mixed JS/TS on the same TS project so I'm not sure. I'll try and get back to you.

You can add QuickJS (and nodeJS?) to the list of supported engine if you are okay with passing the 2 additional argument to the Schema() prototype ;)

**Comment by yne** [comment]
I just tested and --allowJs seems to do the job (but got no typehint on the error() return values)

I'll close this as typescript is not a goal and keeping JS won't block usage.

I'll send a PR with the changes I did to make it work on every platform like node/quickjs (which require the move some global object into the class to forward them the platform fetch/URL)
